print("yahya: As-salamualikum")
print("father:wa-alikum-us-salam")
print("yahya:please give me phone")
print("father:no")
print("yahya:please")
print("father:no")
print("yahya:ok fine")
print("father:I will you at evening ")
print("yahya:ya ho ")