spaces=' '*25
print(f'{spaces}12 Butts Wynd')
print(f'{spaces}Twinklebottom Heat')
print(f'{spaces}West snoring')
print()
print()
print('Dear sir')
print()
print('I Wish to report that tiles are missing frome the')
print('outside toilet roof')
print('I think it was bad wind the other night that blew them away')
print()
print('Regards')
print('Malcolm Dithering')